# Generated by Django 2.0 on 2020-07-13 09:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AdminUsers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account', models.CharField(max_length=32, verbose_name='账户名(email号)')),
                ('password', models.CharField(max_length=64, verbose_name='密码')),
                ('username', models.CharField(max_length=32, verbose_name='真实用户名')),
            ],
            options={
                'db_table': 'adminusers',
            },
        ),
        migrations.CreateModel(
            name='Story',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, verbose_name='故事名')),
                ('storyimg', models.CharField(max_length=64, verbose_name='游戏封面')),
                ('descrip', models.CharField(max_length=1024, verbose_name='游戏介绍')),
                ('status', models.BooleanField(default=False, verbose_name='是否发布')),
                ('editor', models.ForeignKey(db_column='editorid', db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, to='Editor.AdminUsers', verbose_name='后台用户id')),
            ],
            options={
                'db_table': 'story',
            },
        ),
        migrations.CreateModel(
            name='StoryType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('typename', models.CharField(max_length=64, verbose_name='故事类型名称')),
            ],
            options={
                'db_table': 'storytype',
            },
        ),
        migrations.AddField(
            model_name='story',
            name='storytype',
            field=models.ForeignKey(db_column='storytypeid', db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, to='Editor.StoryType', verbose_name='故事类型id'),
        ),
    ]
