# Generated by Django 2.0 on 2020-07-13 09:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Editor', '0001_initial'),
        ('Interaction', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userchoice',
            name='stroy',
            field=models.ForeignKey(db_column='storyid', db_constraint=False, default=None, on_delete=django.db.models.deletion.DO_NOTHING, to='Editor.Story', verbose_name='故事外键'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='users',
            name='email',
            field=models.CharField(default=None, max_length=32, verbose_name='邮箱号'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='users',
            name='password',
            field=models.CharField(default=None, max_length=64, verbose_name='用户密码'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='users',
            name='phonenum',
            field=models.CharField(default=None, max_length=16, verbose_name='手机号'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='userchoice',
            name='user',
            field=models.ForeignKey(db_column='userid', db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, to='Interaction.Users', verbose_name='user外键'),
        ),
        migrations.AlterModelTable(
            name='userchoice',
            table='userchoice',
        ),
        migrations.AlterModelTable(
            name='users',
            table='uses',
        ),
    ]
