# Generated by Django 2.0 on 2020-07-13 09:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Interaction', '0002_auto_20200713_0958'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='users',
            table='users',
        ),
    ]
