# Generated by Django 2.0 on 2020-07-13 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Interaction', '0003_auto_20200713_0958'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userchoice',
            old_name='chapter',
            new_name='chapterid',
        ),
        migrations.AlterField(
            model_name='users',
            name='bgmSound',
            field=models.IntegerField(default=20, verbose_name='背景音乐音量'),
        ),
        migrations.AlterField(
            model_name='users',
            name='dubbingSound',
            field=models.IntegerField(default=20, verbose_name='配音音量'),
        ),
        migrations.AlterField(
            model_name='users',
            name='soundEffects',
            field=models.IntegerField(default=20, verbose_name='游戏音效音量'),
        ),
    ]
